### ISSUE TITLE
Shorten Method Length

### ISSUE THREAD

**Issue by MKlaassen** [vwigmore/HI_HG#56]
Some methods have more than 15 lines. We should try to refactor those.

**Comment by vwigmore** [comment]
These methods are too long according to SIG
![image](https://cloud.githubusercontent.com/assets/9844091/15819572/41fb8946-2be4-11e6-8e57-dc95643f1232.png)
![image](https://cloud.githubusercontent.com/assets/9844091/15819529/0504063a-2be4-11e6-80ea-2d408886d76f.png)

**Comment by MKlaassen** [comment]
Great work everyone! SIG is no longer complaining about long methods.
